<a href="https://colab.research.google.com/github/yashmitha-code/NASSCOM/blob/main/NPMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from numpy._core.fromnumeric import prod
# Core imports for the whole lab
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix

sns.set_theme(style='whitegrid')   # nicer default plot styling
np.random.seed(42)                 # reproducible results
print('Setup complete. NumPy', np.__version__, '| Pandas', pd.__version__)

# -----------------------------------------------------------
# 🔹 1A. ARRAY CREATION & SHAPE
# -----------------------------------------------------------

# arange() builds a range; reshape() changes the shape without copying data
a = np.arange(6).reshape(2, 3)
print('Array a:\n', a)

# Inspect the array's structure
print('shape :', a.shape)
print('ndim  :', a.ndim)
print('dtype :', a.dtype)
print()

# -----------------------------------------------------------
# 🔹 1B. SLICING & INDEXING
# -----------------------------------------------------------

print('Column index 1 :', a[:, 1])
print('Row index 0    :', a[0, :])

# Boolean mask: keep only the elements that satisfy a condition
print('Elements > 2   :', a[a > 2])
print()

# -----------------------------------------------------------
# 🔹 1C. BROADCASTING
# -----------------------------------------------------------

# Broadcasting lets NumPy combine arrays of different shapes without loops
row = np.array([10, 20, 30])   # shape (3,)
print('a + row (row added to every row of a):\n', a + row)
print()

# -----------------------------------------------------------
# 🔹 1D. MATRIX MULTIPLICATION + AXIS-WISE OPERATIONS
# -----------------------------------------------------------

b = np.ones((3, 2), dtype=int)
print('Matrix product a @ b:\n', a @ b)

# Axis-wise reductions: axis=0 collapses rows, axis=1 collapses columns
print('Column-wise sum  (axis=0):', a.sum(axis=0))
print('Row-wise sum     (axis=1):', a.sum(axis=1))
print('Row-wise mean    (axis=1):', a.mean(axis=1))
print('Index of max per column  :', a.argmax(axis=0))
print()

# Given data
M = np.arange(1, 13).reshape(3, 4)   # shape (3, 4)
N = np.arange(1, 9).reshape(4, 2)    # shape (4, 2)
print('M:\n', M)
print('N:\n', N)

# 1. Matrix product M @ N
# YOUR CODE HERE
print("Matrix product M @ N :\n",M @ N)
# 2. Column-wise sum (axis=0) and row-wise mean (axis=1) of M
# YOUR CODE HERE
print('Column-wise sum  (axis=0):', M.sum(axis=0))
print('Row-wise mean    (axis=1):', M.mean(axis=1))
# 3. Index of the max value in each row of M (hint: argmax with axis=1)
# YOUR CODE HERE
print('Index of max per column  :', M.argmax(axis=1))
print()


#PANDAS
# -----------------------------------------------------------
# 🔹 2A. LOAD & INSPECT
# -----------------------------------------------------------

# Load the classic Titanic dataset (built into seaborn).
# In your own work this would be: pd.read_csv('titanic.csv')
df = sns.load_dataset('titanic')

print('Shape:', df.shape)
df.head()
print()

# .info() shows columns, dtypes and non-null counts -> spot missing data fast
df.info()
print()

# .describe() gives summary statistics for the numeric columns
df.describe()


Setup complete. NumPy 2.0.2 | Pandas 2.2.2
Array a:
 [[0 1 2]
 [3 4 5]]
shape : (2, 3)
ndim  : 2
dtype : int64

Column index 1 : [1 4]
Row index 0    : [0 1 2]
Elements > 2   : [3 4 5]

a + row (row added to every row of a):
 [[10 21 32]
 [13 24 35]]

Matrix product a @ b:
 [[ 3  3]
 [12 12]]
Column-wise sum  (axis=0): [3 5 7]
Row-wise sum     (axis=1): [ 3 12]
Row-wise mean    (axis=1): [1. 4.]
Index of max per column  : [1 1 1]

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
N:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Matrix product M @ N :
 [[ 50  60]
 [114 140]
 [178 220]]
Column-wise sum  (axis=0): [15 18 21 24]
Row-wise mean    (axis=1): [ 2.5  6.5 10.5]
Index of max per column  : [3 3 3]

Shape: (891, 15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex